# Generated by Django 4.1.13 on 2024-04-29 00:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FileDefault',
            fields=[
                ('rec', models.CharField(default=api.models.generate_id, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('text_file', models.ImageField(upload_to='assets/')),
                ('speaker', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextDefault',
            fields=[
                ('rec', models.CharField(default=api.models.generate_id, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('text', models.CharField(max_length=5000)),
                ('speaker', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
