# Generated by Django 4.1.13 on 2024-04-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedefault',
            name='text_file',
            field=models.ImageField(upload_to='api'),
        ),
    ]
