# Generated by Django 4.1.13 on 2024-04-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_filedefault_text_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedefault',
            name='text_file',
            field=models.FileField(upload_to='api/'),
        ),
    ]
